### ISSUE TITLE
Stability and Webdav Issues

### ISSUE THREAD

**Issue by patriclougheed** [povsod/mahara-artefact-cloud#2]
Testing these on my Dev 15.10.1 install. Enabling Dropbox and Drive causes 500 error on site:

[WAR] 78 (artefact/cloud/blocktype/dropbox/lib.php:48) Undefined offset: 0

Call stack (most recent first):
log_message("Undefined offset: 0", 8, true, true, "/var/www/htdocs/artefact/cloud/blockty...", 48) at /var/www/htdocs/lib/errors.php:441
error(8, "Undefined offset: 0", "/var/www/htdocs/artefact/cloud/blockty...", 48, array(size 8)) at /var/www/htdocs/artefact/cloud/blocktype/dropbox/lib.php:48
PluginBlocktypeDropbox::render_instance(object(BlockInstance), true) at Unknown:0
call_user_func_array(array(size 2), array(size 2)) at /var/www/htdocs/lib/mahara.php:1705
call_static_method("PluginBlocktypeDropbox", "render_instance", object(BlockInstance), true) at /var/www/htdocs/blocktype/lib.php:885
BlockInstance->render_editing(false, true) at /var/www/htdocs/lib/view.php:2154
View->addblocktype(array(size 5)) at /var/www/htdocs/lib/view.php:1836
View->process_changes() at /var/www/htdocs/view/blocks.json.php:30

[WAR] 78 (artefact/cloud/blocktype/dropbox/lib.php:482) Undefined variable: SESSION

Call stack (most recent first):
log_message("Undefined variable: SESSION", 8, true, true, "/var/www/htdocs/artefact/cloud/blockty...", 482) at /var/www/htdocs/lib/errors.php:441
error(8, "Undefined variable: SESSION", "/var/www/htdocs/artefact/cloud/blockty...", 482, array(size 12)) at /var/www/htdocs/artefact/cloud/blocktype/dropbox/lib.php:482
PluginBlocktypeDropbox::get_filelist("", array(size 0), "3") at /var/www/htdocs/artefact/cloud/blocktype/dropbox/lib.php:49
PluginBlocktypeDropbox::render_instance(object(BlockInstance), true) at Unknown:0
call_user_func_array(array(size 2), array(size 2)) at /var/www/htdocs/lib/mahara.php:1705
call_static_method("PluginBlocktypeDropbox", "render_instance", object(BlockInstance), true) at /var/www/htdocs/blocktype/lib.php:885
BlockInstance->render_editing(false, true) at /var/www/htdocs/lib/view.php:2154
View->addblocktype(array(size 5)) at /var/www/htdocs/lib/view.php:1836
View->process_changes() at /var/www/htdocs/view/blocks.json.php:30

OwnCloud does not seem to connect to Webdav and I can confirm my install of Owncloud works fine with Webdav as I use the mobile app and desktop app to sync files:

[WAR] 3f (artefact/cloud/blocktype/owncloud/lib.php:381) Can't access ownCloud via WebDAV. Incorrect user credentials.

Call stack (most recent first):
PluginBlocktypeOwncloud::get_filelist(0array(size 0), "3") at /var/www/htdocs/artefact/cloud/blocktype/owncloud/lib.php:45
PluginBlocktypeOwncloud::render_instance(object(BlockInstance)) at Unknown:0
call_user_func_array(array(size 2), array(size 1)) at /var/www/htdocs/lib/mahara.php:1705
call_static_method("PluginBlocktypeOwncloud", "render_instance", object(BlockInstance)) at /var/www/htdocs/blocktype/lib.php:1006
BlockInstance->render_viewing(false) at /var/www/htdocs/lib/view.php:2076
View->build_column(3, 1, false, false) at /var/www/htdocs/lib/view.php:2030
View->build_columns(3, false, false) at /var/www/htdocs/lib/view.php:2015
View->build_rows() at /var/www/htdocs/user/view.php:93

**Comment by anzeljg** [comment]
Patric hi.

Would it be possible to create an account for testing purposes for me. I have one other testing account for ownCloud and it seems to work.

**Comment by patriclougheed** [comment]
Happy to... the weird thing is there is nowhere to add login info and there are no prompts. Is the webdav block meant for a single user instance of owncloud? I am running 8.2.1 of ownCloud by the way. I tried using an account that is ldap so username and login is the same for both but still get error so not sure how auth is being passed.
![2016-02-09 13_24_02-folioz beta](https://cloud.githubusercontent.com/assets/1463351/12931021/78928434-cf30-11e5-9b45-da7d44f5dfc0.jpg)

**Comment by patriclougheed** [comment]
Alright... I see that if I do not add access through the Cloud services menu then webdav will fail. Would it not be better to ask for access when adding the block, or add to the error message that they need to add access? When I do add access I get an error when adding the block and get no file list:

![2016-02-09 13_34_38-folioz ca_8080 says_](https://cloud.githubusercontent.com/assets/1463351/12931625/8ea191c2-cf33-11e5-9b48-ca4d97256ec1.jpg)

If a user does not go through the Cloud services page and add access to the other services like Dropbox the server will throw a 500 error when the user tries to edit their pages. I think this has great potential but the workflow for a user is not obvious.

**Comment by anzeljg** [comment]
Good point. I will try to do something about the workflow.

**Comment by anzeljg** [comment]
Issue resolved. New versions (for Mahara 15.04 and Mahara 15.10) released.
