### ISSUE TITLE
Owncloud does not display files

### ISSUE THREAD

**Issue by patriclougheed** [povsod/mahara-artefact-cloud#4]
Able to authorize but when trying to view files I receive JSON error.

![2016-02-23 12_26_35-folioz ca_8080 says_](https://cloud.githubusercontent.com/assets/1463351/13265944/899389e0-da2a-11e5-9730-47ffd88322a6.jpg)

File tree never loads after this. Using Owncloud 8.2.1 and Mahara 5.10.1

**Comment by anzeljg** [comment]
Patric hi.

Strange, because it works for me. I've tested it against ownCloud 8.0.4 and Mahara 15.10.0

Is there a way that you could create a testing account on your ownCloud installation for me to test this?

**Comment by patriclougheed** [comment]
I sure can... I use LDAP for my auth in Mahara and Owncloud so the account will give you access to all. I have sent it to you through your mahara.org account as I do not have your email.

**Comment by anzeljg** [comment]
Issue resolved in latest versions of the plugin:
- for Mahara 15.04: https://github.com/povsod/mahara-artefact-cloud/releases/tag/v15.04.2
- for Mahara 15.10: https://github.com/povsod/mahara-artefact-cloud/releases/tag/v15.10.1
