### ISSUE TITLE
Git submodules - directory structure

### ISSUE THREAD

**Issue by azrek** [povsod/mahara-artefact-cloud#6]
Hi Gregor,

This is just a request. It's not a bug.

In my company, we use Git submodules quite heavily. So, when I clone your repo and include it as a submodule in Mahara, the command is:

git submodule add https://github.com/povsod/mahara-artefact-cloud.git htdocs/artefact/cloud

It creates the directory as:

htdocs/artefact/cloud/cloud

Which is  one directory too deep.

I can't created it as:

git submodule add https://github.com/povsod/mahara-artefact-cloud.git htdocs/artefact

Because that directory already exists.

If I manually move the files, I will have problems merging your changes in the future.

Would it be possible if you moved your files under your repo so they're at the top of the tree - i.e. without the 'cloud' sub-directory?

Moodle plugins organise their repos this way (i.e. files at the top of the tree without a sub-directory). It would be good to be consistent.

Again, this is not a bug. If you can't move them, I completely understand.

Thanks for all the work you've put into this. It's greatly appreciated.

Cheers,
Ghada

**Comment by anzeljg** [comment]
I will think about that...

**Comment by anzeljg** [comment]
Changed directory structure so that it is compatible with git submodules.

For Mahara 15.04: https://github.com/povsod/mahara-artefact-cloud/releases/tag/v15.04.3
For Mahara 15.10: https://github.com/povsod/mahara-artefact-cloud/releases/tag/v15.10.2
